export const MY_TASKS_LIST_REQUEST = "MY_TASKS_LIST_REQUEST";
export const MY_TASKS_LIST_SUCCESS = "MY_TASKS_LIST_SUCCESS";
export const MY_TASKS_LIST_FAIL = "MY_TASKS_LIST_FAIL";

export const MY_TASKS_CREATE_REQUEST = "MY_TASKS_CREATE_REQUEST";
export const MY_TASKS_CREATE_SUCCESS = "MY_TASKS_CREATE_SUCCESS";
export const MY_TASKS_CREATE_FAIL = "MY_TASKS_CREATE_FAIL";

export const MY_TASKS_UPDATE_REQUEST = "MY_TASKS_UPDATE_REQUEST";
export const MY_TASKS_UPDATE_SUCCESS = "MY_TASKS_UPDATE_SUCCESS";
export const MY_TASKS_UPDATE_FAIL = "MY_TASKS_UPDATE_FAIL";

export const MY_TASKS_DELETE_REQUEST = "MY_TASKS_DELETE_REQUEST";
export const MY_TASKS_DELETE_SUCCESS = "MY_TASKS_DELETE_SUCCESS";
export const MY_TASKS_DELETE_FAIL = "MY_TASKS_DELETE_FAIL";

